# Generated by Django 5.2.14 on 2026-05-16 16:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1778948344/ej0fbx9tm9didlovl2bv.jpg', max_length=255, verbose_name='avatar'),
            preserve_default=False,
        ),
    ]
