# Generated by Django 5.2.14 on 2026-05-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default='TEMP', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='package_type',
            field=models.CharField(choices=[('featured_job', 'Gói đẩy tin nổi bật (Nhà tuyển dụng)'), ('compare_job', 'Gói so sánh công việc (Ứng viên)')], default='TEMP', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='skills', to='recruitments.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('momo', 'MoMo'), ('paypal', 'PayPal')], default='momo', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang xử lý'), ('success', 'Thành công'), ('failed', 'Thất bại')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
