# Generated by Django 5.2.14 on 2026-05-20 08:53

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1779188891/y0ddz7zeo9gd4jiejygz.jpg', max_length=255, verbose_name='avatar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='recruitments.category'),
            preserve_default=False,
        ),
    ]
