# Generated by Django 5.2.14 on 2026-05-20 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0003_alter_company_logo_alter_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='recruitments.job'),
        ),
    ]
