# Generated by Django 5.2.14 on 2026-05-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='skills', to='recruitments.category'),
        ),
    ]
